// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A tutorial generator AI agent.
 *
 * - generateTutorial - A function that handles the tutorial generation process.
 * - GenerateTutorialInput - The input type for the generateTutorial function.
 * - GenerateTutorialOutput - The return type for the generateTutorial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTutorialInputSchema = z.object({
  prompt: z.string().describe('The prompt to generate a tutorial from.'),
});
export type GenerateTutorialInput = z.infer<typeof GenerateTutorialInputSchema>;

const GenerateTutorialOutputSchema = z.object({
  tutorial: z.string().describe('The generated tutorial.'),
  progress: z.string().describe('A short summary of the generated tutorial.')
});
export type GenerateTutorialOutput = z.infer<typeof GenerateTutorialOutputSchema>;

export async function generateTutorial(input: GenerateTutorialInput): Promise<GenerateTutorialOutput> {
  return generateTutorialFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTutorialPrompt',
  input: {schema: GenerateTutorialInputSchema},
  output: {schema: GenerateTutorialOutputSchema},
  prompt: `You are an expert tutorial generator. You will generate a tutorial from the given prompt. The tutorial should include explanations, code snippets, links for documentation, and more.\n\nPrompt: {{{prompt}}}`,
});

const generateTutorialFlow = ai.defineFlow(
  {
    name: 'generateTutorialFlow',
    inputSchema: GenerateTutorialInputSchema,
    outputSchema: GenerateTutorialOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return {
      ...output!,
      progress: 'Generated a tutorial from the given prompt.'
    };
  }
);
