"use client";

import { useState } from "react";
import { useForm, type SubmitHandler } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { generateTutorial } from "@/ai/flows/generate-tutorial";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { useToast } from "@/hooks/use-toast";
import type { Project, TutorialStep } from "@/lib/types";
import { Sparkles, Loader2 } from "lucide-react";

const formSchema = z.object({
  prompt: z.string().min(10, {
    message: "Prompt must be at least 10 characters.",
  }),
});

type FormValues = z.infer<typeof formSchema>;

interface GenerateTutorialFormProps {
  addProject: (project: Project) => void;
}

const parseTutorialText = (text: string, prompt: string): Project => {
  const lines = text.split('\n');
  
  const titleLine = lines.find(line => line.startsWith('# ')) || `# ${prompt}`;
  const title = titleLine.replace(/^#\s*/, '').trim();

  const stepChunks: string[][] = [];
  let currentChunk: string[] = [];

  const titleIndex = lines.findIndex(line => line.startsWith('# '));
  const contentStartIndex = titleIndex !== -1 ? titleIndex + 1 : 0;

  for (let i = contentStartIndex; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith('## ') && currentChunk.length > 0) {
      stepChunks.push(currentChunk);
      currentChunk = [line];
    } else {
      currentChunk.push(line);
    }
  }
  if (currentChunk.length > 0) {
    stepChunks.push(currentChunk);
  }
  
  const descriptionLines = stepChunks[0] && !stepChunks[0][0].startsWith('## ') 
    ? stepChunks.shift()!
    : [];
  
  const description = descriptionLines.join('\n').trim();

  const steps: TutorialStep[] = stepChunks.map((chunk, index) => {
    const stepTitleLine = chunk.find(line => line.startsWith('## ')) || `Step ${index + 1}`;
    const stepTitle = stepTitleLine.replace(/^##\s*/, '').replace(/Step \d+:\s*/, '').trim();
    const stepContent = chunk.filter(line => !line.startsWith('## ')).join('\n').trim();
    
    return {
      id: `step-${index + 1}`,
      title: stepTitle,
      content: stepContent,
      completed: false,
    };
  });

  return {
    id: `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${Date.now()}`,
    title,
    description: description || "A new project generated by AI.",
    image: `https://placehold.co/600x400.png?text=${encodeURIComponent(title)}`,
    dataAiHint: title.split(' ').slice(0, 2).join(' ').toLowerCase(),
    steps,
  };
};

export function GenerateTutorialForm({ addProject }: GenerateTutorialFormProps) {
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: { prompt: "" },
  });

  const onSubmit: SubmitHandler<FormValues> = async (data) => {
    setIsLoading(true);
    try {
      const result = await generateTutorial({ prompt: data.prompt });
      const newProject = parseTutorialText(result.tutorial, data.prompt);
      addProject(newProject);
      toast({
        title: "Tutorial Generated!",
        description: `Project "${newProject.title}" has been added.`,
      });
      form.reset();
    } catch (error) {
      console.error("Failed to generate tutorial:", error);
      toast({
        variant: "destructive",
        title: "Oh no! Something went wrong.",
        description: "There was a problem generating the tutorial. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="max-w-3xl mx-auto">
      <CardHeader>
        <CardTitle className="font-headline text-2xl flex items-center">
          <Sparkles className="mr-2 h-6 w-6 text-primary" />
          Generate a New Project Tutorial
        </CardTitle>
        <CardDescription>
          Describe the project you want to build, and our AI will create a step-by-step guide for you.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="prompt"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Project Idea</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="e.g., 'A blog built with Next.js and MDX', 'A real-time chat application using Firebase'"
                      className="resize-none"
                      rows={4}
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Button type="submit" disabled={isLoading} className="w-full sm:w-auto">
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                "Forge Project"
              )}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
